const fanComments = [
  { email: "tex*********@gmail.com", comment: "That beard, that hat, that voice = ICON." },
  { email: "hea********@yahoo.com", comment: "Never disappoints. Ever." },
  { email: "mus*********@yahoo.com", comment: "I’ve followed Chris since his early days. Watching him grow into a legend has been a journey I’m proud to be a part of. He’s more than an artist—he’s family to his fans." },
  { email: "cou*********@gmail.com", comment: "The lyrics always speak to something deeper." },
  { email: "cou*********@gmail.com", comment: "‘Tennessee Whiskey’ will never get old. Ever." },
  { email: "cou*********@gmail.com", comment: "Chris connects to the working class in a real way." },
  { email: "hea********@yahoo.com", comment: "His concert in Nashville in 2022 changed my life. It was intimate, powerful, and emotional. I still get goosebumps thinking about it." },
  { email: "mus*********@yahoo.com", comment: "Chris has a gift. You can feel every emotion in his voice." },
  { email: "tex*********@gmail.com", comment: "He doesn’t need flashy outfits or gimmicks. His talent alone fills stadiums. That’s what true artistry looks like." },
  { email: "ken*********@gmail.com", comment: "When Chris sings live, it’s almost spiritual." },
  { email: "mus*********@yahoo.com", comment: "Voice of our generation." },
  { email: "blu**********@icloud.com", comment: "He doesn’t chase trends, he sets them." },
  { email: "joh******@gmail.com", comment: "Just... wow." },
  { email: "ken*********@gmail.com", comment: "From 'Broken Halos' to 'Fire Away,' Chris has always made music that heals. I turn to him when I need hope, strength, or just a moment of peace." },
  { email: "whi***********@live.com", comment: "I waited 5 years to see Chris live. It was worth every second. The atmosphere, the fans, the voice—it felt like church." },
  { email: "joh******@gmail.com", comment: "He’s unreal." },
  { email: "mus*********@yahoo.com", comment: "Songs that hit deep." },
  { email: "mel***********@gmail.com", comment: "Chris Stapleton’s lyrics hit harder than any other artist. There’s something real about his voice that connects to people of all walks of life." },
  { email: "ken*********@gmail.com", comment: "That voice! 🔥" },
  { email: "cou*********@gmail.com", comment: "You hear one verse and you know it’s him." },
  { email: "mus*********@yahoo.com", comment: "His voice is like velvet and whiskey—smooth and deep." },
  { email: "blu**********@icloud.com", comment: "Chris deserves every award and more." },
  { email: "ban*********@hotmail.com", comment: "Gives me goosebumps!" },
  { email: "joh******@gmail.com", comment: "I feel lucky to be alive at the same time as him." },
  { email: "nas***********@outlook.com", comment: "He’s what country music needed again." },
  { email: "whi***********@live.com", comment: "Pure talent. No autotune needed." },
  { email: "mus*********@yahoo.com", comment: "His songs feel like a conversation with an old friend." },
  { email: "sou***********@aol.com", comment: "His Tiny Desk performance was pure gold." },
  { email: "mus*********@yahoo.com", comment: "Best male voice in country music, hands down." },
  { email: "tex*********@gmail.com", comment: "Chris’s music got me through my military service." },
  { email: "tex*********@gmail.com", comment: "Lyrics that heal." },
  { email: "mel***********@gmail.com", comment: "He deserves all the love this community gives him." },
  { email: "blu**********@icloud.com", comment: "Makes me cry happy tears." },
  { email: "sou***********@aol.com", comment: "Every time I hear 'You Should Probably Leave,' it feels like he's telling my story. Chris’s ability to convey emotion is unmatched in country music today." },
  { email: "cou*********@gmail.com", comment: "Stapleton’s soul shows in every guitar strum." },
  { email: "mel***********@gmail.com", comment: "His voice can silence a crowd in the best way." },
  { email: "ken*********@gmail.com", comment: "‘Parachute’ still slaps like it did on day one." },
  { email: "hea********@yahoo.com", comment: "His concerts feel like family reunions." },
  { email: "nas***********@outlook.com", comment: "I cried the first time I heard ‘Daddy Doesn’t Pray Anymore.’" },
  { email: "ken*********@gmail.com", comment: "I’ve got every vinyl. Fan for life." },
  { email: "tex*********@gmail.com", comment: "‘Joy of My Life’ is our wedding song. Thank you, Chris!" },
  { email: "cou*********@gmail.com", comment: "Chris is the reason I fell back in love with country music." },
  { email: "cou*********@gmail.com", comment: "I introduced my kids to his music and now we sing 'Starting Over' in the car every morning. He brings families together through his music." },
  { email: "mus*********@yahoo.com", comment: "No one can touch him vocally—he’s one of a kind." },
  { email: "blu**********@icloud.com", comment: "He’s the truth in an industry full of noise." },
  { email: "mus*********@yahoo.com", comment: "My favorite artist, period." },
  { email: "cou*********@gmail.com", comment: "Even my mom loves him—and she’s picky!" },
  { email: "tex*********@gmail.com", comment: "He’s simply magical." },
  { email: "hea********@yahoo.com", comment: "Chris forever 💯" },
  { email: "nas***********@outlook.com", comment: "He's a legend in the making—wait, scratch that, he already is." },
  { email: "tex*********@gmail.com", comment: "When I’m driving through the South, it’s always Stapleton." },
  { email: "ban*********@hotmail.com", comment: "Chris Stapleton's music has helped me through heartbreaks, celebrations, and everything in between. His voice is soulful, raw, and genuine—he’s the soundtrack to my life." },
  { email: "mus*********@yahoo.com", comment: "Real music. Real heart." },
  { email: "ban*********@hotmail.com", comment: "I love how grounded and humble he is. True legend." },
  { email: "blu**********@icloud.com", comment: "I’ve never heard someone put so much soul into every word." },
  { email: "mel***********@gmail.com", comment: "Chris makes songs for the heart, not just the charts." },
  { email: "blu**********@icloud.com", comment: "Best to ever do it." },
  { email: "joh******@gmail.com", comment: "His songs speak truths we’re often afraid to say." },
  { email: "mus*********@yahoo.com", comment: "Stapleton’s voice gives me chills every time." },
  { email: "sou***********@aol.com", comment: "The way Chris blends blues, soul, and country is magic. He’s not just a singer; he’s a storyteller, and every note he sings carries weight." },
  { email: "tex*********@gmail.com", comment: "I've converted so many friends into fans." },
  { email: "joh******@gmail.com", comment: "Stapleton never disappoints. Every album is a masterpiece." },
  { email: "mel***********@gmail.com", comment: "He’s why I love country." },
  { email: "whi***********@live.com", comment: "I’m obsessed." },
  { email: "blu**********@icloud.com", comment: "Every album is better than the last." },
  { email: "cou*********@gmail.com", comment: "Absolute legend." },
  { email: "tex*********@gmail.com", comment: "King of live performances." },
  { email: "tex*********@gmail.com", comment: "Country soul. Enough said." },
  { email: "nas***********@outlook.com", comment: "He doesn’t just sing—he bleeds passion." },
  { email: "blu**********@icloud.com", comment: "Stapleton = GOAT." },
];
